// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lerixmbdnqawbwpcbrfu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxlcml4bWJkbnFhd2J3cGNicmZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU1NTkzNTYsImV4cCI6MjA5MTEzNTM1Nn0.NZetqxB_rX0WK7PUiYXfe5NAvyxwf8jvA77z3xR_4tg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});