// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvxbkyciuhnshbckqgzi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2eGJreWNpdWhuc2hiY2txZ3ppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU3MjI4NjIsImV4cCI6MjA5MTI5ODg2Mn0.f4ycCVeJKvJ4tTLhUQhnzc4CvTzBvkupZ47IStizcH0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});