// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbzwqnmxstavnvqadhsc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpiendxbm14c3Rhdm52cWFkaHNjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU1NDMzOTAsImV4cCI6MjA5MTExOTM5MH0.kVLgcZFwlbhDrjNOCNFYhHBlj1GibSiRh4hJZYMXCF0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});